<a href="https://colab.research.google.com/github/finesketch/data_science/blob/main/red_wine_quality.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Red Wine Quality

There is a red winequality dataset which is quite famous. This dataset has 11 different attributes that  decide the quality of red wine.  

These attributes include:
- fixed acidity
- volatile acidity
- citric acid
- residual sugar
- chlorides
- free sulfur dioxide
- total sulfur dioxide
- density
- pH
- sulphates
- alcohol  

Based on these different attributes, we are required to predict the quality of red wine  which is a value between 0 and 10. 

How to solve the *overfitting* for this dataset.

We can treat this problem either as a classification problem or as a regression  problem since wine quality is nothing but a real number between 0 and 10. For  simplicity, letâ€™s choose classification.

> Reference: Thakur, Abhishek. Approaching (Almost) Any Machine Learning Problem.

In [1]:
import pandas as pd

# https://www.kaggle.com/uciml/red-wine-quality-cortez-et-al-2009?select=winequality-red.csv
df = pd.read_csv('winequality-red.csv')

In [3]:
df.head(10)

   fixed acidity  volatile acidity  citric acid  ...  sulphates  alcohol  quality
0            7.4              0.70         0.00  ...       0.56      9.4        5
1            7.8              0.88         0.00  ...       0.68      9.8        5
2            7.8              0.76         0.04  ...       0.65      9.8        5
3           11.2              0.28         0.56  ...       0.58      9.8        6
4            7.4              0.70         0.00  ...       0.56      9.4        5
5            7.4              0.66         0.00  ...       0.56      9.4        5
6            7.9              0.60         0.06  ...       0.46      9.4        5
7            7.3              0.65         0.00  ...       0.47     10.0        7
8            7.8              0.58         0.02  ...       0.57      9.5        7
9            7.5              0.50         0.36  ...       0.80     10.5        5

[10 rows x 12 columns]

In [4]:
# mapping dictionary that maps the quality values from 0 to 5 
quality_mapping = {
    3:0,
    4:1,
    5:2,
    6:3,
    7:4,
    8:5
}

# use the map function of pandas to convert the values in a given column
df.loc[:, 'quality'] = df.quality.map(quality_mapping)